### PR TITLE
Update apiversion

### PR DESCRIPTION
**Pull request by markvincze**
The apiVersion `extensions/v1beta1` was deprecated in 1.16: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

This PR updates the k8s client SDK we're using to its latest version, and changes the apiVersions.

### CODE REVIEW

**Comment by JorritSalverda** [comment]
I think we should switch to `k8s.io/client-go/`, since it's maintained by the Kubernetes community. Most estafette controllers have already made the switch.

**Review by vitorarins — APPROVED** [review]

**Comment by markvincze** [comment]
@JorritSalverda I'll check that.

**Comment by markvincze** [comment]
@JorritSalverda I've migrated it to the official k8s client. (Hope didn't make any mistakes, I couldn't fully test locally, I'll finish the testing in the clusters.)

**Review by JorritSalverda — APPROVED** [review]

**Comment by markvincze** [comment]
@JorritSalverda Could you merge it when you'll have a minute? (I don't have merge permissions)

**Pull request merged**
